name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t todo-api .

    - name: Run Docker container (test only)
      run: docker run -d -p 5000:5000 --name test-todo-api todo-api

    - name: Wait for container to initialize
      run: sleep 5

    - name: Test API
      run: |
        curl --fail http://localhost:5000 || exit 1

    - name: Cleanup
      run: docker stop test-todo-api && docker rm test-todo-api
